https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
https://matplotlib.org/cheatsheets/_images/cheatsheets-1.png
https://www.kaggle.com/code/themlphdstudent/cheat-sheet-seaborn-charts
https://docs.streamlit.io/library/cheatsheet
https://docs.streamlit.io/streamlit-community-cloud/get-started
https://docs.streamlit.io/streamlit-community-cloud/get-started/deploy-an-app
https://github.com/dicodingacademy/a555-dashboard/blob/main/requirements.txt
https://github.com/rfajri27/a555-dashboard/blob/main/README.md
https://www.dicoding.com/academies/555/discussions
https://www.dicoding.com/academies/555/tutorials/31230/submission-guidance
